server:
   context-path: /demo
   port: 8082
security:
  user:
    name: admin
    password: test
spring:
  application:
    name: admin-managee
  datasource:
    druid:
#      最大活跃数
      max-active: 20
      initial-size: 1
      min-idle: 3
#      最大连接数
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,log4j,config
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAImzzq5jMcRkXtEE7jKAZmnHqyKW1OC1qXTidqXkXsVo5a77S0JC4DsutCelBgT88TEpzlVHMBAjlYahssgZQzMCAwEAAQ==
      stat-view-servlet:
        login-username: lfp
        login-password: lfp
        url-pattern: /druid/*
        reset-enable: false
        allow: 10.98.56.181,10.98.56.184,127.0.0.1
      web-stat-filter:
        url-pattern: /*
        exclusions: \*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      url: jdbc:mysql://localhost:3306/caoyi?serverTimezone=UTC
      username: root
#    lfp1991lfp
      password: e59duRga+h9Dt19TL6TlLhrkG/P3f2CHjDIioqkMPk59G8JebRWRta0BS7iJtNMKR0Y0PYS/sqcPlEIqJ3XDlw==
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
      serialization:
         write-dates-as-timestamps: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  aop:
    proxy-target-class: true
springfox:
   documentation:
      swagger:
         v2:
           path: /api-docs
management:
  security:
    enabled: false

mybatis:
  type-aliases-package: tk.mybatis.springboot.model
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  pageSizeZero: true
mapper:
  mappers:
     - com.example.config.mapper.MyMapper
  not-empty: false
  identity: MYSQL
