server:
   context-path: /demo
   port: 8082
security:
  user:
    name: admin
    password: test
spring:
  application:
    name: admin-managee
  datasource:
    url: jdbc:mysql://localhost:3306/caoyi?serverTimezone=UTC
    username: root
    password: lfp1991lfp
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  jackson:
        serialization:
            write-dates-as-timestamps: false
springfox:
   documentation:
      swagger:
         v2:
           path: /api-docs
management:
  security:
    enabled: false

mybatis:
  type-aliases-package: tk.mybatis.springboot.model
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  pageSizeZero: true
mapper:
  not-empty: false
  identity: MYSQL
  mappers: com.example.config.MyMapper
